-- 
-- grants.sql USERNAME - shows the grants to a given user
--

SELECT 'GRANT ' || PRIVILEGE || ' TO ' || GRANTEE || CASE WHEN ADMIN_OPTION = 'YES' THEN ' WITH ADMIN OPTION' ELSE '' END || ';'
FROM DBA_SYS_PRIVS
WHERE GRANTEE = '&&1';

SELECT 'GRANT ' || GRANTED_ROLE || ' TO ' || GRANTEE || CASE WHEN ADMIN_OPTION = 'YES' THEN ' WITH ADMIN OPTION' ELSE '' END || ';'
FROM DBA_ROLE_PRIVS
WHERE GRANTEE = '&&1';

SELECT 'GRANT ' || PRIVILEGE || ' ON ' || OWNER || '.' || TABLE_NAME || ' TO ' || GRANTEE || ';'
FROM DBA_TAB_PRIVS
WHERE GRANTEE = '&&1';